config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, 
             controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  # request email from users signed in with twitter
  match '/users/:id/add_email' => 'users#add_email', 
        via: [:get, :patch, :post], 
        as: :add_user_email

  resources :missions do
    scope module: :mission do 
      resource :sponsorship, only: [:create, :destroy]
      resource :torch, only: [:create, :destroy]
    end
  end
  match '/missions/:id/flag' => 'missions#flag', via: [:patch, :put], as: :flag_mission

  resources :messages
  
  resources :categories
end

app/models/mission.rb
class Mission < ActiveRecord::Base

  ANYONE_CAN_SPONSOR = 1
  ONLY_INVITED_FRIENDS_CAN_SPONSOR = 2

  ANYONE_CAN_SEE_MY_NAME = 1
  ONLY_SPONSORS_CAN_SEE_MY_NAME = 2

  validates_presence_of :title, :category_id

  mount_uploader :image, ImageUploader

  belongs_to :owner,
              class_name: 'User',
              foreign_key: 'user_id'

  belongs_to :category

  has_many :flags, dependent: :destroy

  has_many :torches, dependent: :destroy

  has_many :sponsorships, dependent: :destroy

  # record unique visits/views/impressions on an instance of Mission
  is_impressionable :counter_cache => true, :column_name => :views_cache

  alias_attribute :reason, :description

  scope :flagged, -> { joins(:flags).uniq }

  scope :not_flagged, -> { where.not(id: Flag.select(:mission_id).uniq) }

  scope :flagged_by, ->(user) { flagged.where(mission_flags: {user_id: user.id}) }

  # TODO: should we also add .references for :category and :owner?
  default_scope { includes(:category, :owner, :flags, :sponsorships, :torches) }

  # using .where on this .includes forces AR to use .references which then translates to:
  # missions which have been flagged but not by this user. that's not what we want. instead we'll
  # fetch all missions and filter in the application layer
  # scope :not_flagged_by, ->(user) { includes(:flags).where.not(mission_flags: {user_id: user.id}) }

  def views
    self.views_cache
  end

  def flagged_by? user
    # TODO: run benchmarks. Which is better, loop through all the flags (note these are already loaded 
    # by the default .includes scope) or send a separate query here
    # flag = self.flags.find_by reporter: user
    # flag.nil? ? false : true
    self.flags.each do |flag|
      return true if flag.reporter == user
    end
    false
  end

  def sponsored_by? user
    # TODO: run benchmarks. Which is better, loop through all the sponsorships (note these are already loaded 
    # by the default .includes scope) or send a separate query here
    # sponsorship = self.sponsorships.find_by sponsor: user
    # sponsorship.nil? ? false : true
    self.sponsorships.each do |sponsorship|
      return true if sponsorship.sponsor == user
    end
    false
  end

  def torched_by? user
    # TODO: run benchmarks. Which is better, loop through all the torches (note these are already loaded 
    # by the default .includes scope) or send a separate query here
    # torch = self.torches.find_by torcher: user
    # torch.nil? ? false : true
    self.torches.each do |torch|
      return true if torch.torcher == user
    end
    false
  end
end

app/models/mission/flag.rb
class Mission::Flag < ActiveRecord::Base
  belongs_to :mission
  belongs_to :reporter,
              class_name: 'User',
              foreign_key: 'user_id'
end

app/models/mission/sponsorship.rb
class Mission::Sponsorship < ActiveRecord::Base
  belongs_to :mission
  belongs_to :sponsor,
              class_name: 'User',
              foreign_key: 'user_id'
end

app/models/mission/torch.rb
class Mission::Torch < ActiveRecord::Base
  belongs_to :mission
  belongs_to :torcher,
              class_name: 'User',
              foreign_key: 'user_id'
end

app/controllers/mission/sponsorships_controller.rb
class Mission::SponsorshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_mission
  before_action :ensure_current_user_can_sponsor_mission!, only: :create
  before_action :ensure_current_user_already_sponsors_mission!, only: :destroy

  # POST /missions/:mission_id/sponsorship
  # POST /missions/:mission_id/sponsorship.json
  def create
    if @mission.sponsored_by? current_user
      return respond_to do |format|
        format.html { redirect_to mission_path(@mission) }
        format.json { head :no_content }
      end
    end
    @mission.sponsorships.create sponsor: current_user
    respond_to do |format|
      # TODO: notification and activity
      format.html { redirect_to mission_path(@mission), notice: t('missions.sponsored_successfully') }
      format.json { render json: { count: @mission.sponsorships.count } }
    end
  end

  # DELETE /missions/:mission_id/sponsorship
  # DELETE /missions/:mission_id/sponsorship.json
  def destroy
    sponsorhip = @mission.sponsorships.find_by sponsor: current_user
    sponsorhip.destroy
    respond_to do |format|
      format.html { redirect_to mission_path(@mission) }
      format.json { render json: { count: @mission.sponsorships.count } }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find(params[:mission_id])
    end

    def ensure_current_user_can_sponsor_mission!
      # TODO: can you sponsor your own mission?
      if current_user == @mission.owner
        redirect_to missions_url, alert: t('missions.cannot_sponsor_own_mission')
      elsif @mission.sponsored_by? current_user
        redirect_to missions_url, notice: t('missions.already_sponsoring_mission')
      elsif @mission.who_can_sponsor != Mission::ANYONE_CAN_SPONSOR
        redirect_to missions_url, flash: { error: t('missions.edit_sponshorship_denied') }
      end
    end

    def ensure_current_user_already_sponsors_mission!
      if not @mission.sponsored_by? current_user
        redirect_to missions_url, flash: { error: t('missions.destroy_sponshorship_denied') }
      end
    end
end

app/controllers/mission/torches_controller.rb
class Mission::TorchesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_mission

  # POST /missions/:mission_id/torch
  # POST /missions/:mission_id/torch.json
  def create
    if @mission.torched_by? current_user
      return respond_to do |format|
        format.html { redirect_to mission_path(@mission) }
        format.json { head :no_content }
      end
    end
    @mission.torches.create torcher: current_user
    respond_to do |format|
      # TODO: notification and activity
      format.html { redirect_to mission_path(@mission), notice: t('missions.torch_awarded_successfully') }
      format.json { render json: { count: @mission.torches.count } }
    end
  end

  # DELETE /missions/:mission_id/torch
  # DELETE /missions/:mission_id/torch.json
  def destroy
    torch = @mission.torches.find_by torcher: current_user
    torch.destroy
    respond_to do |format|
      format.html { redirect_to mission_path(@mission) }
      format.json { render json: { count: @mission.torches.count } }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find(params[:mission_id])
    end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_mission, only: [:show, :edit, :update, :destroy, :flag]
  before_action :ensure_current_user_can_update_mission!, only: [:edit, :update, :destroy]
  before_action :ensure_current_user_can_view_mission!, only: [:show]
  before_action :set_categories, only: [:new, :edit]

  # TODO: I18n flash messages
  # TODO: sending sponsorship invitations

  # GET /missions
  # GET /missions.json
  def index
    # TODO: rules for featured missions: image correct size (1920x415).
    # TODO later: featured only approved by admin
    filter = params[:filter] || 'featured'
    case filter
    when 'featured'
      @listed = Mission.all
      @showcased = Mission.not_flagged.where.not(image: nil).limit(5)
    end
  end

  # GET /missions/1
  # GET /missions/1.json
  def show
    # one has to be signed in to view a mission, so it's safe to use the session hash
    # as a filter for unique views
    impressionist @mission, "viewed by #{current_user.id}", :unique => [:session_hash]
  end

  # GET /missions/new
  def new
    @mission = Mission.new
  end

  # GET /missions/1/edit
  def edit
  end

  # POST /missions
  # POST /missions.json
  def create
    @mission = Mission.new(mission_params)
    @mission.owner = current_user

    respond_to do |format|
      if @mission.save
        format.html { redirect_to @mission, notice: 'Mission was successfully created.' }
        format.json { render :show, status: :created, location: @mission }
      else
        format.html { render :new }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missions/1
  # PATCH/PUT /missions/1.json
  def update
    respond_to do |format|
      if @mission.update(mission_params)
        format.html { redirect_to @mission, notice: 'Mission was successfully updated.' }
        format.json { render :show, status: :ok, location: @mission }
      else
        format.html { render :edit }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/1
  # DELETE /missions/1.json
  def destroy
    @mission.destroy
    respond_to do |format|
      format.html { redirect_to missions_url }
      format.json { head :no_content }
    end
  end

  # PATCH/PUT /missions/1/flag
  # PATCH/PUT /missions/1/flag.json
  def flag
    respond_to do |format|
      if @mission.flagged_by?(current_user) || @mission.flags.create(reporter: current_user)
        # TODO: if flagged count exceeds minimum allowed flags till it's taken down automatically,
        # notify user, mark as flagged so no one sees it
        # TODO: redirect_to :back (in order to apply whichever filter was active i.e. featured, recent etc)
        format.html { redirect_to missions_url, notice: t('missions.flagged_as_inappropriate') }
        format.json { head :accepted }
      else
        # TODO: redirect_to :back (in order to apply whichever filter was active i.e. featured, recent etc)
        format.html { redirect_to missions_url, alert: t('missions.could_not_flag_as_inappropriate') }
        format.json { head :internal_server_error }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find(params[:id])
    end

    def set_categories
      @categories = Category.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mission_params
      params.require(:mission).permit(:title, :description, :image, :image_cache, :remove_image, 
                                      :category_id, :location, :deadline, :who_can_sponsor, 
                                      :who_can_see_my_name)
    end

    def ensure_current_user_can_update_mission!
      if @mission.owner != current_user
        redirect_to missions_url, flash: { error: t('missions.edit_access_denied') }
      end
    end

    def ensure_current_user_can_view_mission!
      unless @mission.owner == current_user ||
        @mission.who_can_see_my_name == Mission::ANYONE_CAN_SPONSOR ||
        @mission.sponsored_by?(current_user)
        redirect_to missions_url, alert: t('missions.view_access_denied')
      end
    end
end

app/helpers/mission/sponsorships_helper.rb
module Mission::SponsorshipsHelper
  def can_sponsor_mission? mission
    # TODO: can you sponsor your own mission?
    return false if current_user == mission.owner
    return false if mission.sponsored_by? current_user
    return true if mission.who_can_sponsor == Mission::ANYONE_CAN_SPONSOR
    # TODO: invitees should be automatically added to the list of sponsors
  end

  def sponsor_button_class mission
    return 'activated' if mission.sponsored_by? current_user
    if can_sponsor_mission? mission
      'activate'
    else
      'disabled'
    end
  end
end

app/helpers/mission/torches_helper.rb
module Mission::TorchesHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
  def can_update_mission? mission
    mission.owner == current_user
  end

  def can_see_mission_owner_name? mission
    mission.owner == current_user ||
    mission.who_can_see_my_name == Mission::ANYONE_CAN_SEE_MY_NAME ||
    mission.sponsored_by?(current_user)
    # TODO: should we also let invitees who haven't accepted their invitations to see the name too?
  end

  def can_view_mission? mission
    mission.owner == current_user ||
    mission.who_can_see_my_name == Mission::ANYONE_CAN_SPONSOR ||
    mission.sponsored_by?(current_user)
  end
end

app/views/missions/_form.html.erb
<div class="fixed-width">
  <%= form_for @mission, html: { role: 'form' } do |f| %>

    <%= render 'partials/form_errors', item: @mission %>

    <div class="field">
      <%= f.text_field :title, placeholder: t('missions.form.vision') %>
    </div>

    <div class="field image_field" id="image_field">
      <% if @mission.image? %>
        <%= image_tag @mission.image.url %>
        <%= f.label t('missions.form.picture'), style: 'display: none', 'data-unsupported' => t('missions.form.file_api_unsupported') %>
        <div class="buttons">
          <button id="remove_image" data-message="<%= t('missions.form.remove_image_confirm') %>"><%= t('missions.form.remove_image') %></button>
          <button id="change_image"><%= t('missions.form.change_image') %></button>
          <button id="add_image" style="display: none"><%= t('missions.form.add_image') %></button>
        </div>
        <%= f.check_box :remove_image %>
      <% else %>
        <%= f.label t('missions.form.picture'), 'data-unsupported' => t('missions.form.file_api_unsupported') %>
        <img style="display: none" src="#" alt="">
        <div class="buttons">
          <button id="remove_image" data-message="<%= t('missions.form.remove_image_confirm') %>"><%= t('missions.form.remove_image') %></button>
          <button id="change_image" style="display: none"><%= t('missions.form.change_image') %></button>
          <button id="add_image"><%= t('missions.form.add_image') %></button>
        </div>
      <% end %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
    </div>
    <p class="help" id="chosen_image"><%= @mission.image? ? File.basename(@mission.image.path) : t('missions.form.allowed_image_types') %></p>

    <div class="field-row">
      <div class="category">
        <span><i></i></span>
        <%= f.select :category_id, @categories.collect {|c| [c.name, c.id] }, prompt: t('missions.form.category') %>
      </div>
      <div class="location">
        <span><i></i></span>
        <%= f.text_field :location, placeholder: t('missions.form.location') %>
      </div>
      <div class="deadline">
        <span><i></i></span>
        <%= f.text_field :deadline, 
                          placeholder: t('missions.form.deadline'), 
                          id: 'deadline', 
                          'data-date-format' => t('missions.form.date_format_for_datepicker'),
                          'data-date-autoclose' => true,
                          value: @mission.deadline? ? @mission.deadline.strftime(t('missions.form.date_format')) : '' %>
      </div>
    </div>

    <div class="field">
      <%= f.text_area :description, rows: 1, placeholder: t('missions.form.reason') %>
    </div>

    <div class="title">
      <%= t('missions.form.privacy') %>
    </div>

    <div class="field field-row">
      <div class="radio_label"><%= t('missions.form.who_can_sponsor') %></div>
      <label class="first">
        <%= f.radio_button :who_can_sponsor, Mission::ANYONE_CAN_SPONSOR, { checked: @mission.who_can_sponsor != Mission::ONLY_INVITED_FRIENDS_CAN_SPONSOR } %>
        <%= t('missions.form.anyone_can_sponsor', site_name: Rails.application.config.site_name) %>
      </label>
      <label class="second">
        <%= f.radio_button :who_can_sponsor, Mission::ONLY_INVITED_FRIENDS_CAN_SPONSOR %>
        <%= t('missions.form.only_invited_friends_can_sponsor') %>
      </label>
    </div>

    <div class="field field-row">
      <div class="radio_label"><%= t('missions.form.who_can_see_my_name') %></div>
      <label class="first">
        <%= f.radio_button :who_can_see_my_name, Mission::ANYONE_CAN_SEE_MY_NAME, { checked: @mission.who_can_see_my_name != Mission::ONLY_SPONSORS_CAN_SEE_MY_NAME } %>
        <%= t('missions.form.anyone_can_see_my_name', site_name: Rails.application.config.site_name) %>
      </label>
      <label class="second">
        <%= f.radio_button :who_can_see_my_name, Mission::ONLY_SPONSORS_CAN_SEE_MY_NAME %>
        <%= t('missions.form.only_sponsors_can_see_my_name') %>
      </label>
    </div>

    <div class="actions">
      <%= f.submit t('missions.form.update') %>
    </div>
  <% end %>
</div>

app/views/missions/_mission_actions.html.erb
<p class="actions" data-container="<%= container %>">
  <button class="torches <%= mission.torched_by?(current_user) ? 'activated' : 'activate' %>"
      data-url="<%= mission_torch_path mission %>"
      data-create-error="<%= t 'missions.could_not_award_torch' %>"
      data-destroy-error="<%= t 'missions.could_not_revoke_torch' %>">
    <i></i> 
    <span><%= mission.torches.size %></span>
  </button>
  <% class_name = sponsor_button_class mission %>
  <button class="sponsors <%= class_name %>"
    <% if class_name == 'disabled' %>
      <%= raw 'disabled="disabled"' %>
    <% else %>
      data-url="<%= mission_sponsorship_path mission %>"
      data-create-error="<%= t 'missions.could_not_sponsor' %>"
      data-destroy-error="<%= t 'missions.could_not_unsponsor' %>"
    <% end %>>
    <i></i>
    <span><%= mission.sponsorships.size %></span>
  </button>
  <button class="shares">
    <i></i> 0
  </button>
</p>

app/views/missions/_mission_title_and_info.html.erb
<h3><%= can_view_mission?(mission) ? link_to(mission.title, mission) : mission.title %></h3>
<p class="info">
  <% if can_see_mission_owner_name? mission %>
  <span class="owner"><%= t 'missions.by' %> <%= mission.owner.name %></span>
  <% end %>
  <% if mission.location? %>
  <span class="location"><%= mission.location %></span>
  <% end %>
  <span class="time"><%= time_ago_in_words mission.created_at %> <%= t 'missions.ago' %></span>
  <span class="views"><%= pluralize mission.views, t('missions.views') %> </span>
  <span class="category"><%= mission.category.name %></span>
</p>

app/views/missions/_mission_title_and_meta.html.erb
<h3><%= link_to mission.title, mission %></h3>
<p class="meta">
  <span class="owner"><%= t 'missions.by' %> <%= mission.owner.name %></span>
  <% if mission.location? %>
  <span class="location"><%= mission.location %></span>
  <% end %>
  <span class="time"><%= time_ago_in_words mission.created_at %> <%= t 'missions.ago' %></span>
  <span class="views"><%= pluralize mission.views, t('missions.views') %> </span>
  <span class="category"><%= mission.category.name %></span>
</p>

app/views/missions/edit.html.erb
<h1>Editing mission</h1>

<%= render 'form' %>

<%= link_to 'Show', @mission %> |
<%= link_to 'Back', missions_path %>

app/views/missions/index.html.erb
<h1>Listing missions</h1>

<div id="missions">

  <p><%= link_to t('missions.new_mission'), new_mission_path %></p>

  <% if @showcased.any? %>
  <div class="showcased carousel slide" data-ride="carousel" id="showcased-missions">

    <ul class="missions carousel-inner">
      <% @showcased.each_with_index do |mission, index| %>
      <li class="mission item <%= 'active' if index == 0 %>" data-mission-id="<%= mission.id %>">
        <%= image_tag mission.image.url, alt: mission.title %>
        <div class="caption carousel-caption">
          <div class="top">
            <%= render 'mission_title_and_info', mission: mission %>
          </div>
          <div class="bottom">
            <% # TODO: don't show full reason by default %>
            <% if mission.reason? %>
            <p><%= mission.reason %></p>
            <% end %>
            <%= render 'mission_actions', mission: mission, container: '#showcased-missions' %>
            </p>
          </div>
        </div>
      </li>
      <% end %>
    </ul>

    <ol class="carousel-indicators">
      <li data-target="#showcased-missions" data-slide-to="0" class="active"></li>
      <% for i in 1..(@showcased.size-1) %>
      <li data-target="#showcased-missions" data-slide-to="<%= i %>"></li>
      <% end %>
    </ol>

  </div>
  <% end %>

  <% if @listed.any? %>
  <div class="listed" id="listed-missions">
    <ul class="missions">
      <% @listed.each_with_index do |mission| %>
      <% next if mission.flagged_by? current_user %>
      <li>
        <div class="mission <%= 'accomplished' if mission.accomplished? %>" data-mission-id="<%= mission.id %>">
          <% if mission.accomplished? %>
          <span class="accomplished"><%= t 'missions.accomplished' %></span>
          <% end %>
          <% if can_update_mission? mission %>
            <div class="options" title="<%= t('missions.edit_or_delete') %>">
              <div>
                <a data-toggle="dropdown" href="#"></a>
                <ul role="menu">
                  <li><%= link_to t('missions.edit'), edit_mission_path(mission) %></li>
                  <li><%= link_to t('missions.delete'), mission, method: :delete, data: { confirm: t('missions.delete_confirmation') } %></li>
                </ul>
              </div>
            </div>
          <% else %>
            <div class="flag" data-toggle="tooltip" data-placement="auto top" title="<%= t('missions.flag_as_inappropriate') %>">
              <div>
                <a data-toggle="dropdown" href="#"></a>
                <ul role="menu">
                  <li><span><%= t('missions.flag_as_inappropriate_confirmation') %></span></li>
                  <li class="buttons">
                    <button class="ok" 
                            data-method="<%= :patch %>" 
                            data-url="<%= flag_mission_path(mission, format: :json) %>" 
                            data-message-flagged="<%= t('missions.flagged_as_inappropriate') %>" 
                            data-message-flag-error="<%= t('missions.could_not_flag_as_inappropriate') %>">
                            <%= t('dialogs.confirm.ok') %></button>
                    <button class="cancel"><%= t 'dialogs.confirm.cancel' %></button>
                  </li>
                </ul>
              </div>
            </div>
            
          <% end %>

          <%= render 'mission_title_and_info', mission: mission %>

          <% if mission.image? %>
          <div class="img">
            <% image = image_tag mission.image.url, alt: mission.title %>
            <%= can_view_mission?(mission) ? link_to(image, mission) : image %>
          </div>
          <% end %>

          <%= render 'mission_actions', mission: mission, container: '#listed-missions' %>

          <% # TODO: don't show full reason by default %>
          <% if mission.reason? %>
          <p class="reason"><%= mission.reason %></p>
          <% end %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
  <% else %>

  <p><%= t 'missions.no_missions' %> <%= link_to t('missions.new_mission'), new_mission_path %></p>

  <% end %>

</div>

app/views/missions/new.html.erb
<h1>New mission</h1>

<%= render 'form' %>

<%= link_to 'Back', missions_path %>

app/views/missions/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @mission.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @mission.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @mission.image.url if @mission.image? %>
</p>

<% if can_update_mission? @mission %>
<%= link_to 'Edit', edit_mission_path(@mission) %> |
<% end %>
<%= link_to 'Back', missions_path %>